
version: 2
jobs:
  ami-build:
    docker:
      - image: hashiCorp/packer:1.1.1
    working_directory: ~/packer
    - run:
          name: Validate ami.json
          command: packer validate ami.json
  ami-build:
    docker:
      - image: hashicorp/packer:1.1.1  
    steps:
      - checkout
      - run:
          name: Build ami.json
          command: packer build ami.json  
workflows:
  version: 2
  packer:
    jobs:   
      - ami-build:
          context: ec2
            


          
