
version: 2
jobs:
  buildami:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer  
    steps:
      - checkout
      - run:
          name: Build ami.json
          command: packer build ami.json
workflows:
  version: 2
  amipacker:
    jobs:   
      - buildami
            

    
          
